services:
  db:
    image: postgres:latest
    env_file:
      - .env_db
    ports:
      - '5432:5432'


  web:
    build:
      context: .
      dockerfile: Dockerfile_web
    env_file:
      - .env_web
    ports:
      - '5173:5173'
    depends_on:
      - db

  api:
    build:
      context: .
      dockerfile: Dockerfile_api
    env_file:
      - .env_api
    ports:
      - '3000:3000'
    depends_on:
      - db
