#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER ${DB_N8N_USER} WITH PASSWORD '${DB_N8N_PASSWORD}';
	CREATE DATABASE ${DB_N8N_DATABASE};
	GRANT ALL PRIVILEGES ON DATABASE ${DB_N8N_DATABASE} TO ${DB_N8N_USER};
	\c ${DB_N8N_DATABASE} ${POSTGRES_USER}
	GRANT ALL ON SCHEMA public TO ${DB_N8N_USER};
EOSQL
