sonar.projectKey=MuNuChapterHKN_HKrecruitment
sonar.organization=munuchapterhkn
sonar.projectName=HKrecruitment

sonar.javascript.lcov.reportPaths=./shared-unit-coverage-report/lcov.info, ./api-unit-coverage-report/lcov.info, ./api-e2e-coverage-report/lcov.info
sonar.sources=api/, frontend/, shared/
sonar.coverage.exclusions=**/node_modules/**/*, **/*.spec.*, **/*.e2e-spec.*, **/documentation/**/*, **/frontend/**/*, **/test/**/*, **/tests/**/*, **/*.json, **/*.yaml, **/*.yml, **/*.md, **/mocks/**/*
sonar.cpd.exclusions=**/mocks/**/*
