sonar.projectKey=MuNuChapterHKN_HKrecruitment
sonar.organization=munuchapterhkn
sonar.projectName=HKrecruitment

sonar.javascript.lcov.reportPaths=./coverage/shared/lcov.info, ./coverage/api/lcov.info, ./coverage/api-e2e/lcov.info
sonar.sources=api/, frontend/, shared/
sonar.coverage.exclusions=**/node_modules/**/*, **/*.spec.*, **/test/**/*, **/tests/**/*, **/*.json, **/*.yaml, **/*.yml, **/*.md
