/*
 * Copyright (c) 2021 Riccardo Zaccone
 *
 * This file is part of hkrecruitment-apiserver.
 * hkrecruitment-apiserver is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * hkrecruitment-apiserver is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with hkrecruitment-apiserver.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * File:   NotificationSubsystem.ts
 * Project: hkrecruitment-apiserver
 * Authors:
 * Riccardo Zaccone <riccardo.zaccone at hknpolito.org>
 *
 * Created on 21 aprile 2021, 18:16
 */

import {NotificationEvent, NotificationMethod} from "../config/recruitmentConfig";
import {Notifier} from "./Notifier";
import {Compensator} from "./Compensator";
import {NotificationDAO} from "./DAO/DAOdefs";
import {ConfigManager} from "./ConfigManager";
import {GMailNotifier} from "./GMailNotifier";
import Timeout = NodeJS.Timeout;
import {NotificationTemplates} from "../config/notificationTemplate";
import {Application} from "../datatypes/application";
import {Applicant, Member} from "../datatypes/entities";
import {LangLevel} from "../datatypes/enums";
import {PeriodicEvent} from "./PeriodicEvent";

type Language = "ita" | "eng";
type user_type="applicant" | "member";

const callbackWrapper = async (callback: (ntfS: NotificationSubsystem)=>Promise<void>, ntfS: NotificationSubsystem)=>{
    try{
        await callback(ntfS);
    }
    catch (e) { //Ok, what to do if the callback fails? Simply record it?
        console.error(e);
    }
}

/**
 * Describes parameters to construct a notification
 */
interface NotificationFields{
    uri:string,
    member_id:string,
    applicant_id:string,
    text:string
}

/**
 * Describes parameters to be received by NotificationSubsystem from outside
 */
export interface NotificationData {
    application_id?: number;
    start?: string;
    end?: string;
    customMessage?: {subject:string, body:string};
    additionalText?:string;
    interview_id?: number;
    member_id?: string;
}

/**
 * Describes the data generated by NotificationSubsystem for Notifiers
 */
export interface NotifierData{
    mainRecipient: (Member|Applicant),
    secondaryRecipient: Member | null;
    lang: Language;
    notification: NotificationFields; //Here so to support push notifications without much effort
    start?: string;
    end?: string;
    customMessage?: {subject:string, body:string};
    additionalText?:string;
}

/**
 * @class NotificationSubsystem handles all the aspects related to notification inside the system, that is:
 *  - the creation and consumption of notifications;
 *  - the choice of notification_methods, so the the types of notifier, used for the each
 *    notification_event;
 *
 * More in detail, this class deals with deciding who needs to be notified, while delegates the "how"
 * to the notifiers.
 */
export class NotificationSubsystem{
    private notifiers : Map<NotificationMethod, Notifier>;
    private config: ConfigManager;
    private readonly storage : NotificationDAO;
    private compensator : Compensator;
    private periodic_ntf : Map<string, Timeout>;
    private selector: RecipientsSelector;


    constructor(storage: NotificationDAO, compensator: Compensator, config:ConfigManager) {
        this.storage = storage;
        this.compensator = compensator;
        this.config = config;
        //here set the notifier object for each notification method
        this.notifiers=new Map<NotificationMethod, Notifier>([["email", new GMailNotifier(this.storage)]]);
        this.periodic_ntf=new Map<string, Timeout>();
        this.selector=new RecipientsSelector(this.storage);
    }

    /**
     * Creates a notification and uses the proper notifiers
     * @param event the event that triggers the notification
     * @param data the data about the event occurred
     */
    notify(event:NotificationEvent, data: NotificationData) : Promise<void>{
        return new Promise(async (resolve, reject)=>{
            try{
                const [mainRecipient, secondaryRecipient, user_type, lang]=await this.selector.getRecipients(event, data);
                const n=buildNotification(event, mainRecipient, secondaryRecipient, user_type, lang);
                await this.storage.notifications.insert(n.uri, n.text, n.member_id, n.applicant_id);
                const notifiers: Notifier[]=await this.selectNotifiers(event);
                const promises:Promise<number>[]=[]
                notifiers.forEach((ntf)=>{
                    promises.push(ntf.notify(event,  {...data, mainRecipient, secondaryRecipient, lang, notification: n}));
                });
                Promise.all(promises).then(()=>resolve()).catch((err)=>reject(err));
            }
            catch (e) {
                reject(e);
            }
        });
    }

    /**
     * Registers that an applicant or a member read a notification
     * @param n_id the id of the notification
     * @param user_id the id of the applicant or member
     * @param user_type the type of user, that is "applicant" or "member"
     */
    readNotification(n_id:number, user_id:string, user_type:"member"| "applicant"){
        return this.storage.notifications.read(n_id, user_id, user_type);
    }

    /**
     * Creates one single notification and periodically triggers the proper notifiers to notify the user
     * @param event the periodic event
     * @param entity the entity related to the periodic event
     * @param data the data about the event occurred
     * @param period the interval between two periodic notifications, in minutes
     * @return {Promise<void>} a promise representing whether the setup of a periodic notification was successful
     */
    periodicNotify<T>(event: PeriodicEvent<T>, entity: T, data : NotificationData, period:number):Promise<void>{
        return new Promise(async (resolve, reject)=>{
            try{
                const [mainRecipient, secondaryRecipient, user_type, lang]=await this.selector.getRecipients(event.name, data);
                const n=await buildNotification(event.name, mainRecipient, secondaryRecipient, user_type, lang);
                await this.storage.notifications.insert(n.uri, n.text, n.member_id, n.applicant_id);
                const notifiers: Notifier[]=await this.selectNotifiers(event.name);
                const periodicCallback=(ntfS: NotificationSubsystem):Promise<void>=>{
                    return new Promise<void>((res, rej)=>{
                        if(!event.stillValid(entity)) return ntfS.stopPeriodicNotify(event, entity);
                        const promises:Promise<number>[]=[]
                        notifiers.forEach((ntf)=>{
                            promises.push(ntf.notify(event.name,  {...data, mainRecipient, secondaryRecipient, lang, notification: n}));
                        });
                        //What to do in case of rejection?
                        return Promise.all(promises).then(()=>res()).catch(e=>rej(e));
                    })

                };
                periodicCallback(this).then(()=>{ //execute now and every period
                    this.setPeriodicNotification(event, entity, period, periodicCallback)
                    resolve();
                }).catch(e=>reject(e));
            }
            catch (e) {
                reject(e);
            }
        });
    }
    stopPeriodicNotify<T>(event:PeriodicEvent<T>, entity: T): Promise<void>{
        return new Promise((res, rej)=>{
            const id=event.getId(entity), tm=this.periodic_ntf.get(id);
            if(!tm){
                rej(`Timeout object not present for id ${id}`);
                return;
            }
            clearInterval(tm);
            this.periodic_ntf.delete(id);
            const c=event.needsCompensation(entity);
            if(c)  this.compensator.compensate(c, entity, this).then(()=>res()).catch(e=>rej(e));
        });
    }
    private setPeriodicNotification<T>(event: PeriodicEvent<T>, entity: T, period: number, callback: (ntfS: NotificationSubsystem) => Promise<void>){
        const id:string=event.getId(entity);
        const ms=period*60*1000; //from minutes to milliseconds
        const tm=setInterval(callbackWrapper, ms, callback, this);
        // @ts-ignore
        this.periodic_ntf.set(id, tm);
    }

    /**
     * Retrieves the list of notifiers to be used for the given event
     * @param event the event that triggered the notification
     * @private
     */
    async selectNotifiers(event: NotificationEvent) :Promise<Notifier[]>{
        const notificationStrategies=await this.config.get("notification_strategies");
        const eventMethodsPair=notificationStrategies.find((item)=>item.event===event);
        if(!eventMethodsPair) throw new Error(`Notification methods missing for event ${event}`);
        const notifiers:Notifier[]=[];
        for(const method of eventMethodsPair.methods){
            const ntf=this.notifiers.get(method);
            if (!ntf) throw new Error(`Method not available ${method}`);
            notifiers.push(ntf);
        }
        return notifiers;
    }
}

/**
 * Get the notification text from the templates
 * @param event the event that triggered the notification.
 * @param {Language} lang the language of the notification
 */
function getNotificationTextAndUri(event: NotificationEvent, lang: Language): [string, string] {
    const templates:NotificationTemplates=require(process.cwd()+"/src/config/notificationTemplate.json");
    // @ts-ignore
    return [templates[event][lang], templates[event].uri];
}

export function buildNotification(event: NotificationEvent, mainRecipient: Member | Applicant, secondaryRecipient: Member | null, user_type: user_type, lang: Language): NotificationFields {
    const [text, uri]=getNotificationTextAndUri(event, lang);
    if(user_type==="applicant") {
        if (!secondaryRecipient) throw new Error("Missing member to notify for notification to applicant");
        return {text, uri, applicant_id: mainRecipient.id, member_id: secondaryRecipient.id};
    }
    else
        return {text, uri, applicant_id: "0", member_id: mainRecipient.id};
}

export class RecipientsSelector{
    private storage: NotificationDAO;

    constructor(storage: NotificationDAO) {
        this.storage = storage;
    }

    /**
     * Gets the lists of recipients (main users to be notified) and members that will receive the
     * notification "for knowledge"
     * @param event the event that triggered the notification
     * @param data the data about the event occurred
     */
    async getRecipients(event: NotificationEvent, data: NotificationData): Promise<[(Member | Applicant), Member | null, user_type, Language]> {
        const application_events: NotificationEvent[] = ["application_accepted", "application_revocated", "new_application", "slot_reserved"];
        let member:Member, applicant:Applicant, application:Application;
        //require_availability_confirmation will only trigger notification to the proper member
        if (event === "require_availability_confirmation" || event==="availability_not_required"
            || event==="require_manual_slot_compensation" || event==="request_availability") {
            member=await this.selectMember(data);
            return [member, null, "member", "ita"];
        }
        [applicant, application] = application_events.includes(event) ? //applicant and application from application_id or interview_id
            await this.selectApplicantFromApplication(data) : await this.selectApplicantFromInterview(data);
        member=await this.secondaryRecipient(event, application);
        return [applicant, member, "applicant", RecipientsSelector.notificationLanguage(application.ita_level)];
    }

    /**
     * When an event is about a member, the notification will be directed only to him or her
     * @param data the data about the event occurred. Because the only event that requires notification
     * to a member is request_availability_confirmation, data must contain the parameters of the
     * availability, that is {start, end, member_id}.
     */
    selectMember(data: NotificationData): Promise<Member>{
        if(!data.member_id || !data.start || !data.end) throw new Error("Missing parameters");
        return this.storage.members.get(data.member_id);
    }

    /**
     * When an event is about an application, the main recipient is the applicant whose application
     * belongs to.
     * @param data the data about the event occurred. In this case it must contain the application_id
     * The notification language is chosen on the basis on the italian language level registered in
     * the application.
     */
    async selectApplicantFromApplication(data: NotificationData): Promise<[Applicant, Application]>{
        if (!data.application_id) throw new Error("Missing application_id");
        const mainRecipient = await this.storage.applications.getApplicant(data.application_id);
        const application = await this.storage.applications.get(data.application_id);
        return [mainRecipient, application];
    }

    /**
     * Similar to applicationEvent(), here the application id is retrieved from the interview
     * @param data the data about the event occurred. In this case it must contain the interview_id
     */
    async selectApplicantFromInterview(data: NotificationData): Promise<[Applicant, Application]>{
        if(!data.interview_id) throw new Error("Missing interview_id");
        const interview=await this.storage.interviews.get(data.interview_id)
        const application=this.storage.applications.get(interview.application_id);
        const mainRecipient=this.storage.applications.getApplicant(interview.application_id);
        return [await mainRecipient, await application];
    }

    /**
     * Selects the staff member to notify basing on the event and the application:
     *  - If the event is "application_revocated", a supervisor must be notified;
     *  - If the application had been modified by a clerk, he or she will be notified;
     *  - In any other case, a clerk will be notified:
     *    - If the application refers to a PhD student, a clerk from the board will be chosen
     *    - Otherwise a clerk that is not part of the board;
     * @param event the event that triggered the notification. Cannot be "require_availability_confirmation"
     * @param application the application linked to the event
     */
    async secondaryRecipient(event: NotificationEvent, application: Application): Promise<Member>{
        if (event === "application_revocated") //we need to contact a supervisor
            return oneOf(await this.storage.members.supervisors.list());
        if (application.last_modified)  //if previously modified by staff member, keep notifying him/her
            return this.storage.members.get(application.last_modified.member_id);
        //one of the clerks, look at the application to decide if board members or not
        const clerks=await this.storage.members.clerks.list();
        const selectedClerks=clerks.filter(application.type==="PhD" ?
           (clerk)=>clerk.is_board : (clerk)=>!clerk.is_board);
        return oneOf(selectedClerks);
    }

    /**
     * Selects the language to be used for the notification, basing on the italian language level of the
     * applicant.
     * @param {LangLevel} level the language level of the applicant registered in the application.
     * @return {Language} "ita" if the applicant is a native speaker, "eng" otherwise.
     */
     static notificationLanguage(level: LangLevel): Language{
        return level==="native_speaker" ? "ita":"eng";
    }
}

/**
 * Return one random element of an array of elements
 * @template T
 * @param items<T> an array of items
 * @return {T} an element of the array
 * @throws {Error} if the array is empty
 */
export function oneOf<T>(items: T[]): T{
    if(items.length===0) throw new Error("Empty array");
    return items[Math.floor(Math.random() * items.length)];
}
