/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type MessageKey = "name" | "surname" | "additionalText" | "start" | "end";
export type MessageVocabulary = VocabularyEntry[];

export interface MessageTemplates {
  new_application: MessageTemplate;
  application_accepted: MessageTemplate;
  application_revocated: MessageTemplate;
  require_availability_confirmation: MessageTemplate;
  slot_reserved: MessageTemplate;
  interview_member_accepted: MessageTemplate;
  interview_mentee_accepted: MessageTemplate;
  interview_rejected: MessageTemplate;
}
export interface MessageTemplate {
  ita: Message;
  eng: Message;
}
export interface Message {
  subject: string;
  body: string;
  fields: MessageKey[];
  vocabulary: MessageVocabulary;
}
export interface VocabularyEntry {
  placeholder: string;
  male: string;
  female: string;
}
