/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface NotificationTemplates {
  new_application: NotificationTemplate;
  application_accepted: NotificationTemplate;
  application_revocated: NotificationTemplate;
  require_availability_confirmation: NotificationTemplate;
  slot_reserved: NotificationTemplate;
  interview_member_accepted: NotificationTemplate;
  interview_mentee_accepted: NotificationTemplate;
  interview_rejected: NotificationTemplate;
  availability_not_required: NotificationTemplate;
}
export interface NotificationTemplate {
  ita: string;
  eng: string;
  uri: string;
}
