/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type AvailabilityCompensationMethod =
  | "manual_fallback"
  | "trySubstitution"
  | "searchSubstitution"
  | "reAskTimeSlots";
export type AvailabilityCompensationBroadcasting = "allInterviewers" | "allInterviewersInDay" | "leastNBusy";
export type NotificationEvent =
  | "new_application"
  | "application_accepted"
  | "application_revocated"
  | "require_availability_confirmation"
  | "slot_reserved"
  | "interview_member_accepted"
  | "interview_mentee_accepted"
  | "interview_rejected"
  | "availability_not_required"
  | "request_availability"
  | "reAskTimeSlot"
  | "require_manual_slot_compensation";
export type NotificationMethod = "email" | "push" | "sms" | "telegram";
export type SlotComputationalMethod = "bestFit" | "firstFit";

export interface RecruitmentConfig {
  applicant: {
    timeslots_num: number;
    min_timeslots_chooseAmong: number;
    min_hours_before_first_timeslot: number;
    can_see_interviewers?: boolean;
    [k: string]: unknown;
  };
  member: {
    min_hours_before_interviewer_confirm: number;
    max_slots_day: number;
    max_slots_week: number;
    max_consecutive_slots: number;
    reminder_availability_confirmation_hours: number;
    metrics_weight: {
      gender_inequality: number;
      slots_day: number;
      slots_week: number;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  compensation: {
    availability_compensation_strategies: [
      {
        strategy?: AvailabilityCompensationMethod;
        broadcasting?: AvailabilityCompensationBroadcasting;
        N?: number;
        [k: string]: unknown;
      },
      ...{
        strategy?: AvailabilityCompensationMethod;
        broadcasting?: AvailabilityCompensationBroadcasting;
        N?: number;
        [k: string]: unknown;
      }[]
    ];
    [k: string]: unknown;
  };
  notification_strategies: [
    {
      event: NotificationEvent;
      methods: NotificationMethod[];
      [k: string]: unknown;
    },
    ...{
      event: NotificationEvent;
      methods: NotificationMethod[];
      [k: string]: unknown;
    }[]
  ];
  slot_computational_strategy: SlotComputationalMethod;
  interview_template: string;
  [k: string]: unknown;
}
