import type { Metadata } from 'next';
import { Geist_Mono, Outfit } from 'next/font/google';
import { Toaster } from '@/components/ui/sonner';

import './globals.css';
import { stageColors } from '@/lib/stages';

const outfit = Outfit({
  variable: '--font-outfit',
  weight: ['400', '500', '600'],
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Recruitment Platform for HKN MuNu',
  description: 'Generated by create next app',
};

const stageColorsVars = Object.fromEntries(
  Object.entries(stageColors).map(([k, v]) => ['--color-stage-' + k, v])
);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} ${geistMono.variable} antialiased`}
        style={stageColorsVars}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
