/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GCalendarPreferences {
  gcalendarPreferences?: {
    insert?: Insert;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface Insert {
  conferenceDataVersion?: number;
  sendUpdates?: "all" | "externalOnly" | "none";
  guestsCanInviteOthers?: boolean;
  guestCanModify?: boolean;
  guestCanSeeOtherGuests?: boolean;
  location?: string;
  reminders?: {
    useDefault: boolean;
    overrides: [
      {
        method: "email" | "popup";
        minutes: number;
      },
      ...{
        method: "email" | "popup";
        minutes: number;
      }[]
    ];
    [k: string]: unknown;
  };
  visibility?: "default" | "public" | "private";
  conferenceData?: {
    createRequest: {
      conferenceSolutionKey: {
        type: string;
        [k: string]: unknown;
      };
      requestId?: string;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
