/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {ApplicationState, Gender} from "./enums";
import {BscApplication, MscApplication, PhdApplication} from "./entities";

/**
 * This interface was referenced by `Payloads`'s JSON-Schema
 * via the `definition` "v1MembersInsertRequest".
 */
export type V1MembersInsertRequest = Person;
/**
 * This interface was referenced by `Payloads`'s JSON-Schema
 * via the `definition` "v1MembersPatchRequest".
 */
export type V1MembersPatchRequest = {
  image?: string;
  email?: string;
  phone_no?: string;
  is_board?: boolean;
  is_expert?: boolean;
  role?: "admin" | "supervisor" | "clerk" | "none";
};
export type V1ApplicantsInsertRequest =
    | {
  bsc_application: Application & {
    study_path: string;
    academic_year: number;
    cfu: number;
    grades: string;
    grades_avg: number;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
    | {
  msc_application: Application & {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
    | {
  phd_application: Application & {
    msc_study_path: string;
    phd_description: string;
    [k: string]: unknown;
  };
  cv_raw?: Uint8Array;
  grades_raw?: Uint8Array;
  msc_grades_raw?: Uint8Array;
  [k: string]: unknown;
};
/**
 * This interface was referenced by `Payloads`'s JSON-Schema
 * via the `definition` "v1ApplicantsPatchRequest".
 */
export type V1ApplicantsPatchRequest = {
  [k: string]: unknown;
};
/**
 * This interface was referenced by `Payloads`'s JSON-Schema
 * via the `definition` "v1TimeSlotsGetSlotsAndAvailabilities".
 */
export type V1TimeSlotsGetSlotsAndAvailabilities = {
  time_slot: {
    start: string;
    end: string;
    [k: string]: unknown;
  };
  slots: {
    state: "free" | "assigned" | "reserved" | "rejected";
    cal_id?: string;
    time_slot: {
      start: string;
      end: string;
      [k: string]: unknown;
    };
    members: [
      {
        id: string;
        name: string;
        surname: string;
        sex: "male" | "female";
        image: string;
        is_expert: boolean;
        is_board: boolean;
        [k: string]: unknown;
      },
      {
        id: string;
        name: string;
        surname: string;
        sex: "male" | "female";
        image: string;
        is_expert: boolean;
        is_board: boolean;
        [k: string]: unknown;
      },
      ...{
        id: string;
        name: string;
        surname: string;
        sex: "male" | "female";
        image: string;
        is_expert: boolean;
        is_board: boolean;
        [k: string]: unknown;
      }[]
    ];
    interview_id?: number;
    [k: string]: unknown;
  }[];
  availabilities: {
    state: "subscribed" | "used" | "confirmed" | "usedAndConfirmed" | "cancelled";
    assigned_at?: string;
    confirmed_at?: string;
    time_slot: {
      start: string;
      end: string;
      [k: string]: unknown;
    };
    member_id: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}[];
/**
 * This interface was referenced by `Payloads`'s JSON-Schema
 * via the `definition` "v1NotificationsReadRequest".
 */
export type V1NotificationsReadRequest = {
  [k: string]: unknown;
};

/**
 * This interface was referenced by `Payloads`'s JSON-Schema
 * via the `definition` "v1MembersGetByFullNameRequest".
 */
export interface V1MembersGetByFullNameRequest {
  id: string;
  image: string;
  name: string;
  surname: string;
  sex: "male" | "female";
  [k: string]: unknown;
}

/**
 * This interface was referenced by `Payloads`'s JSON-Schema
 * via the `definition` "v1ApplicantsUpdateFriendListRequest".
 */
export interface V1ApplicantsUpdateFriendListRequest {
  friends: [number, ...number[]];
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Payloads`'s JSON-Schema
 * via the `definition` "v1ApplicantsCheckExistanceResponse".
 */
export interface V1ApplicantsCheckExistanceResponse {
  found: boolean;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Payloads`'s JSON-Schema
 * via the `definition` "v1ApplicantsListFriendsResponse".
 */
export interface V1ApplicantsListFriendsResponse {
  friends: {
    id: string;
    name: string;
    surname: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Payloads`'s JSON-Schema
 * via the `definition` "v1AvailabilitiesListResponse".
 */
export interface V1AvailabilitiesListResponse {
  member_id: string;
  start: string;
  end: string;
  availabilities: {
    state: "subscribed" | "used" | "confirmed" | "usedAndConfirmed" | "cancelled";
    assigned_at?: string;
    confirmed_at?: string;
    time_slot: {
      start: string;
      end: string;
      [k: string]: unknown;
    };
    member_id: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Payloads`'s JSON-Schema
 * via the `definition` "v1AvailabilitiesInsertRequest".
 */
export interface V1AvailabilitiesInsertRequest {
  start: string;
  end: string;
  member_id: string;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Payloads`'s JSON-Schema
 * via the `definition` "v1SlotsGetTimeSlotsResponse".
 */
export interface V1SlotsGetTimeSlotsResponse {
  time_slots: {
    start: string;
    end: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Payloads`'s JSON-Schema
 * via the `definition` "v1SlotsBatchModifyRequest".
 */
export interface V1SlotsBatchModifyRequest {
  time_slot: {
    start: string;
    end: string;
    [k: string]: unknown;
  };
  slots: [
    {
      state: "free" | "assigned" | "reserved" | "rejected";
      cal_id?: string;
      time_slot: {
        start: string;
        end: string;
        [k: string]: unknown;
      };
      members: [
        {
          id: string;
          name: string;
          surname: string;
          sex: "male" | "female";
          image: string;
          is_expert: boolean;
          is_board: boolean;
          [k: string]: unknown;
        },
        {
          id: string;
          name: string;
          surname: string;
          sex: "male" | "female";
          image: string;
          is_expert: boolean;
          is_board: boolean;
          [k: string]: unknown;
        },
        ...{
          id: string;
          name: string;
          surname: string;
          sex: "male" | "female";
          image: string;
          is_expert: boolean;
          is_board: boolean;
          [k: string]: unknown;
        }[]
      ];
      interview_id?: number;
      [k: string]: unknown;
    },
    ...{
      state: "free" | "assigned" | "reserved" | "rejected";
      cal_id?: string;
      time_slot: {
        start: string;
        end: string;
        [k: string]: unknown;
      };
      members: [
        {
          id: string;
          name: string;
          surname: string;
          sex: "male" | "female";
          image: string;
          is_expert: boolean;
          is_board: boolean;
          [k: string]: unknown;
        },
        {
          id: string;
          name: string;
          surname: string;
          sex: "male" | "female";
          image: string;
          is_expert: boolean;
          is_board: boolean;
          [k: string]: unknown;
        },
        ...{
          id: string;
          name: string;
          surname: string;
          sex: "male" | "female";
          image: string;
          is_expert: boolean;
          is_board: boolean;
          [k: string]: unknown;
        }[]
      ];
      interview_id?: number;
      [k: string]: unknown;
    }[]
  ];
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Payloads`'s JSON-Schema
 * via the `definition` "v1SlotsListEligibleResponse".
 */
export interface V1SlotsListEligibleResponse {
  chosen_ts: [
    {
      time_slot: {
        start: string;
        end: string;
        [k: string]: unknown;
      };
      slots: [
        {
          state: "free" | "assigned" | "reserved" | "rejected";
          cal_id?: string;
          time_slot: {
            start: string;
            end: string;
            [k: string]: unknown;
          };
          members: [
            {
              id: string;
              name: string;
              surname: string;
              sex: "male" | "female";
              image: string;
              is_expert: boolean;
              is_board: boolean;
              [k: string]: unknown;
            },
            {
              id: string;
              name: string;
              surname: string;
              sex: "male" | "female";
              image: string;
              is_expert: boolean;
              is_board: boolean;
              [k: string]: unknown;
            },
            ...{
              id: string;
              name: string;
              surname: string;
              sex: "male" | "female";
              image: string;
              is_expert: boolean;
              is_board: boolean;
              [k: string]: unknown;
            }[]
          ];
          interview_id?: number;
          [k: string]: unknown;
        },
        ...{
          state: "free" | "assigned" | "reserved" | "rejected";
          cal_id?: string;
          time_slot: {
            start: string;
            end: string;
            [k: string]: unknown;
          };
          members: [
            {
              id: string;
              name: string;
              surname: string;
              sex: "male" | "female";
              image: string;
              is_expert: boolean;
              is_board: boolean;
              [k: string]: unknown;
            },
            {
              id: string;
              name: string;
              surname: string;
              sex: "male" | "female";
              image: string;
              is_expert: boolean;
              is_board: boolean;
              [k: string]: unknown;
            },
            ...{
              id: string;
              name: string;
              surname: string;
              sex: "male" | "female";
              image: string;
              is_expert: boolean;
              is_board: boolean;
              [k: string]: unknown;
            }[]
          ];
          interview_id?: number;
          [k: string]: unknown;
        }[]
      ];
      availabilities: [
        {
          state: "subscribed" | "used" | "confirmed" | "usedAndConfirmed" | "cancelled";
          assigned_at?: string;
          confirmed_at?: string;
          time_slot: {
            start: string;
            end: string;
            [k: string]: unknown;
          };
          member_id: string;
          [k: string]: unknown;
        },
        ...{
          state: "subscribed" | "used" | "confirmed" | "usedAndConfirmed" | "cancelled";
          assigned_at?: string;
          confirmed_at?: string;
          time_slot: {
            start: string;
            end: string;
            [k: string]: unknown;
          };
          member_id: string;
          [k: string]: unknown;
        }[]
      ];
      [k: string]: unknown;
    },
    ...{
      time_slot: {
        start: string;
        end: string;
        [k: string]: unknown;
      };
      slots: [
        {
          state: "free" | "assigned" | "reserved" | "rejected";
          cal_id?: string;
          time_slot: {
            start: string;
            end: string;
            [k: string]: unknown;
          };
          members: [
            {
              id: string;
              name: string;
              surname: string;
              sex: "male" | "female";
              image: string;
              is_expert: boolean;
              is_board: boolean;
              [k: string]: unknown;
            },
            {
              id: string;
              name: string;
              surname: string;
              sex: "male" | "female";
              image: string;
              is_expert: boolean;
              is_board: boolean;
              [k: string]: unknown;
            },
            ...{
              id: string;
              name: string;
              surname: string;
              sex: "male" | "female";
              image: string;
              is_expert: boolean;
              is_board: boolean;
              [k: string]: unknown;
            }[]
          ];
          interview_id?: number;
          [k: string]: unknown;
        },
        ...{
          state: "free" | "assigned" | "reserved" | "rejected";
          cal_id?: string;
          time_slot: {
            start: string;
            end: string;
            [k: string]: unknown;
          };
          members: [
            {
              id: string;
              name: string;
              surname: string;
              sex: "male" | "female";
              image: string;
              is_expert: boolean;
              is_board: boolean;
              [k: string]: unknown;
            },
            {
              id: string;
              name: string;
              surname: string;
              sex: "male" | "female";
              image: string;
              is_expert: boolean;
              is_board: boolean;
              [k: string]: unknown;
            },
            ...{
              id: string;
              name: string;
              surname: string;
              sex: "male" | "female";
              image: string;
              is_expert: boolean;
              is_board: boolean;
              [k: string]: unknown;
            }[]
          ];
          interview_id?: number;
          [k: string]: unknown;
        }[]
      ];
      availabilities: [
        {
          state: "subscribed" | "used" | "confirmed" | "usedAndConfirmed" | "cancelled";
          assigned_at?: string;
          confirmed_at?: string;
          time_slot: {
            start: string;
            end: string;
            [k: string]: unknown;
          };
          member_id: string;
          [k: string]: unknown;
        },
        ...{
          state: "subscribed" | "used" | "confirmed" | "usedAndConfirmed" | "cancelled";
          assigned_at?: string;
          confirmed_at?: string;
          time_slot: {
            start: string;
            end: string;
            [k: string]: unknown;
          };
          member_id: string;
          [k: string]: unknown;
        }[]
      ];
      [k: string]: unknown;
    }[]
  ];
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Payloads`'s JSON-Schema
 * via the `definition` "v1ApplicationsUpdateTimeSlots".
 */
export interface V1ApplicationsUpdateTimeSlots {
  time_slots: [
    {
      start: string;
      end: string;
      [k: string]: unknown;
    },
    ...{
      start: string;
      end: string;
      [k: string]: unknown;
    }[]
  ];
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Payloads`'s JSON-Schema
 * via the `definition` "v1ApplicationsListResponse".
 */
export interface V1ApplicationsListResponse {
  applications: {
    id: number;
    submission_date: string;
    state: "new" | "accepted" | "rejected" | "confirmed" | "finalized" | "refused_by_applicant";
    applicant: {
      id: string;
      name: string;
      surname: string;
      sex: "male" | "female";
      [k: string]: unknown;
    };
    slot?: {
      state: "free" | "assigned" | "reserved" | "rejected";
      cal_id?: string;
      time_slot: {
        start: string;
        end: string;
        [k: string]: unknown;
      };
      members: [
        {
          id: string;
          name: string;
          surname: string;
          sex: "male" | "female";
          image: string;
          is_expert: boolean;
          is_board: boolean;
          [k: string]: unknown;
        },
        {
          id: string;
          name: string;
          surname: string;
          sex: "male" | "female";
          image: string;
          is_expert: boolean;
          is_board: boolean;
          [k: string]: unknown;
        },
        ...{
          id: string;
          name: string;
          surname: string;
          sex: "male" | "female";
          image: string;
          is_expert: boolean;
          is_board: boolean;
          [k: string]: unknown;
        }[]
      ];
      interview_id?: number;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}

export interface v1ApplicationsInsertRequest {
  application: BscApplication | MscApplication | PhdApplication;
  cv_raw?: Uint8Array;
  grades_raw?: Uint8Array;
  msc_grades_raw?: Uint8Array;
}

export interface V1ApplicationsPatchRequest {
  state?: ApplicationState;
  notes?: string;
  customMessage? : {
    subject: string;
    body: string
  },
  additionalText?: string;
  [k: string]: unknown;
}

/**
 * This interface was referenced by `Payloads`'s JSON-Schema
 * via the `definition` "v1ApplicantsListApplicationsResponse".
 */
export interface V1ApplicantsListApplicationsResponse {
  applications: {
    id: number;
    submission_date: string;
    state: "new" | "accepted" | "rejected" | "confirmed" | "finalized" | "refused_by_applicant";
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Payloads`'s JSON-Schema
 * via the `definition` "v1NotificationListRequest".
 */
export interface V1NotificationListRequest {
  read: (
      | {
    [k: string]: unknown;
  }
      | {
    [k: string]: unknown;
  }
      )[];
  unread: (
      | {
    [k: string]: unknown;
  }
      | {
    [k: string]: unknown;
  }
      )[];
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Payloads`'s JSON-Schema
 * via the `definition` "v1StudyPathsInsertRequest".
 */
export interface V1StudyPathsInsertRequest {
  degree_level: "BSc" | "MSc" | "PhD";
  study_path: string;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Payloads`'s JSON-Schema
 * via the `definition` "v1StudyPathsListResponse".
 */
export interface V1StudyPathsListResponse {
  BSc: string[];
  MSc: string[];
  PhD: string[];
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Payloads`'s JSON-Schema
 * via the `definition` "v1StatisticsDailyInterviewSums".
 */
export interface V1StatisticsDailyInterviewSums {
  start: string;
  end: string;
  stats: {
    day: string;
    daily_stats?: {
      member: {
        id: string;
        name: string;
        surname: string;
        sex: "male" | "female";
        email: string;
        role: "admin" | "supervisor" | "clerk" | "none";
        is_expert: boolean;
        is_board: boolean;
        [k: string]: unknown;
      };
      interviews_n: number;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Payloads`'s JSON-Schema
 * via the `definition` "v1StatisticsTsInterviewSums".
 */
export interface V1StatisticsTsInterviewSums {
  start: string;
  end: string;
  stats: {
    time_slot?: string;
    ts_stats?: {
      member: {
        id: string;
        name: string;
        surname: string;
        sex: "male" | "female";
        email: string;
        role: "admin" | "supervisor" | "clerk" | "none";
        is_expert: boolean;
        is_board: boolean;
        [k: string]: unknown;
      };
      interviews_n: number;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Payloads`'s JSON-Schema
 * via the `definition` "v1StatisticsDailyMemberSlotDistr".
 */
export interface V1StatisticsDailyMemberSlotDistr {
  start: string;
  end: string;
  stats: {
    day?: string;
    male?: number;
    female?: number;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Payloads`'s JSON-Schema
 * via the `definition` "v1StatisticsTsMemberSlotDistr".
 */
export interface V1StatisticsTsMemberSlotDistr {
  start: string;
  end: string;
  stats: {
    time_slot?: string;
    ts_stat?: {
      male?: number;
      female?: number;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Payloads`'s JSON-Schema
 * via the `definition` "v1StatisticsApplicantGenderDistr".
 */
export interface V1StatisticsApplicantGenderDistr {
  start: string;
  end: string;
  stat: {
    male: number;
    female: number;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Payloads`'s JSON-Schema
 * via the `definition` "v1StatisticsMemberAvgResponseTime".
 */
export interface V1StatisticsMemberAvgResponseTime {
  start: string;
  end: string;
  stats: {
    member_id: string;
    response_time: number;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Payloads`'s JSON-Schema
 * via the `definition` "v1StatisticsApplicationStateCount".
 */
export interface V1StatisticsApplicationStateCount {
  start: string;
  end: string;
  stat: {
    male: {
      accepted: number;
      rejected: number;
      refused_by_applicant: number;
      [k: string]: unknown;
    };
    female: {
      accepted: number;
      rejected: number;
      refused_by_applicant: number;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Payloads`'s JSON-Schema
 * via the `definition` "v1StatisticsInterviewOutcomeCount".
 */
export interface V1StatisticsInterviewOutcomeCount {
  start: string;
  end: string;
  stat: {
    male: {
      member_accepted: number;
      mentee_accepted: number;
      rejected: number;
      [k: string]: unknown;
    };
    female: {
      member_accepted: number;
      mentee_accepted: number;
      rejected: number;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
