#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER ${DB_HKR_USER} WITH PASSWORD '${DB_HKR_PASSWORD}';
	CREATE DATABASE ${DB_HKR_DATABASE};
	GRANT ALL PRIVILEGES ON DATABASE ${DB_HKR_DATABASE} TO ${DB_HKR_USER};
	\c ${DB_HKR_DATABASE} ${POSTGRES_USER}
	GRANT ALL ON SCHEMA public TO ${DB_HKR_USER};
EOSQL
