/* tslint:disable */
import {AvailabilityState} from "./enums";

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Notification = {
  [k: string]: unknown;
};

export interface TimeSlot {
  start: string;
  end: string;
  [k: string]: unknown;
}
export interface Availability {
  state: AvailabilityState;
  assigned_at?: string;
  confirmed_at?: string;
  time_slot: TimeSlot;
  member_id: string;
  [k: string]: unknown;
}
export interface Change {
  member_id: string;
  time: string;
  attributes?: string[];
  [k: string]: unknown;
}
