/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type AvailabilityState = "subscribed" | "used" | "confirmed" | "usedAndConfirmed" | "cancelled";
export type InterviewOutcome = "member_accepted" | "mentee_accepted" | "rejected";
export type ApplicationState = "new" | "accepted" | "rejected" | "confirmed" | "finalized" | "refused_by_applicant";
export type SlotState = "free" | "assigned" | "reserved" | "rejected";
export type Gender = "male" | "female";
export type ManRole = "admin" | "supervisor" | "clerk" | "none";
export type LangLevel = "B2" | "C1" | "C2" | "native_speaker";
export type HKNArea =
  | "information_technology"
  | "human_resources"
  | "tutoring"
  | "communication"
  | "events"
  | "corporate_training";
export type DegreeLevel = "BSc" | "MSc" | "PhD";
