name: CI
on:
  push:
    branches:
      - master
jobs:
  Build-Backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
        working-directory: ./api
      - run: npm test
        working-directory: ./api
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_DEV_API_KEY}}
          heroku_app_name: "hkrecruitment-dev-environment"
          heroku_email: ${{secrets.HEROKU_DEV_EMAIL}}
          appdir: "api"
          usedocker: true
