name: Test

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Check fomatting
        run: pnpm run format-check

      - name: Test building
        run: pnpm run build && pnpm run clean

      # - name: Run shared unit tests
      #   run: pnpm --filter shared test:cov > shared_unit.txt &

      # - name: Run api unit tests
      #   run: pnpm --filter api test:cov > api_unit.txt &

      - name: Start all tests
        env:
          DATABASE_TYPE: sqlite
          DATABASE_NAME: ":memory:"
          DATABASE_SYNCHRONIZE: true
          AUTH0_ISSUER_URL: ${{ secrets.TEST_AUTH0_ISSUER_URL }}
          AUTH0_AUDIENCE: ${{ secrets.TEST_AUTH0_AUDIENCE }}
          AUTH0_CLIENT_ID: ${{ secrets.TEST_AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.TEST_AUTH0_CLIENT_SECRET }}
        run:
          sh -c "pnpm --filter shared test:cov >>shared_unit.txt 2>&1" &
          sh -c "pnpm --filter api test:cov >>api_unit.txt 2>&1" &
          sh -c "pnpm --filter api test-e2e:cov >>api_e2e.txt 2>&1" &


      - name: Wait for tests to finish
        run: wait

      - name: Shared unit tests output
        run: cat shared_unit.txt
      
      - name: Api unit tests output
        run: cat api_unit.txt

      - name: Api e2e tests output
        run: cat api_e2e.txt

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}